services:
  web:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./frontend/src:/var/www/html
    env_file:
      - .env.example
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  api:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    env_file:
      - .env.example
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  db:
    image: postgres:15
    container_name: postgres_gps
    restart: always
    env_file:
      - .env.example
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: {}